{"timestamp":"2025-06-26T07:09:27.125603","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-06-26T07:09:27.126756","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/weathers.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-06-26T07:09:27.300174","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-06-26T07:09:27.408318","level":"info","event":"Connection Retrieved 'open_meteo_api'","logger":"airflow.hooks.base"}
{"timestamp":"2025-06-26T07:09:45.039992","level":"warning","event":"HTTPSConnectionPool(host='api.open-meteo.com', port=443): Max retries exceeded with url: /v1/forecast?latitude=14.7&longitude=43.5&current_weather=true (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)'))) Tenacity will retry to execute the operation","logger":"airflow.task.hooks.airflow.providers.http.hooks.http.HttpHook"}
{"timestamp":"2025-06-26T07:09:45.040518","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"SSLError","exc_value":"HTTPSConnectionPool(host='api.open-meteo.com', port=443): Max retries exceeded with url: /v1/forecast?latitude=14.7&longitude=43.5&current_weather=true (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)')))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":838,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1130,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/weathers.py","lineno":33,"name":"extract_weather_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py","lineno":265,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py","lineno":323,"name":"run_and_check"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py","lineno":315,"name":"run_and_check"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":698,"name":"send"}]},{"exc_type":"MaxRetryError","exc_value":"HTTPSConnectionPool(host='api.open-meteo.com', port=443): Max retries exceeded with url: /v1/forecast?latitude=14.7&longitude=43.5&current_weather=true (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)')))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":667,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}]},{"exc_type":"SSLError","exc_value":"[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"}]},{"exc_type":"SSLEOFError","exc_value":"[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":741,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":920,"name":"_ssl_wrap_socket_and_match_hostname"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":480,"name":"ssl_wrap_socket"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":524,"name":"_ssl_wrap_socket_impl"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":455,"name":"wrap_socket"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1041,"name":"_create"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1319,"name":"do_handshake"}]}]}
